#!/usr/bin/env node

/**
 * Generate Manifest Index Files
 *
 * This script automatically generates TypeScript index files for each manifest type.
 * It scans the manifests directory and creates aggregated exports in src/lib/generated/
 *
 * Usage: node scripts/generate-manifest-indexes.ts
 */

import { execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const MANIFESTS_DIR = path.join(__dirname, '../../manifests')
const OUTPUT_DIR = path.join(__dirname, '../../src/lib/generated')

// Manifest types to process
const MANIFEST_TYPES = [
  'ides',
  'clis',
  'desktops',
  'models',
  'providers',
  'extensions',
  'vendors',
] as const

type ManifestType = (typeof MANIFEST_TYPES)[number]

interface ImportData {
  varName: string
  statement: string
  sortKey: string
}

/**
 * Ensure directory exists
 */
function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true })
    console.log(`✓ Created directory: ${dirPath}`)
  }
}

/**
 * Convert kebab-case id to PascalCase variable name
 */
function toPascalCase(str: string): string {
  return str
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}

/**
 * Get all JSON files in a directory
 */
function getJsonFiles(dirPath: string): string[] {
  if (!fs.existsSync(dirPath)) {
    return []
  }
  return fs
    .readdirSync(dirPath)
    .filter(file => file.endsWith('.json'))
    .sort()
}

/**
 * Generate index file for a manifest type
 */
function generateIndexFile(typeName: ManifestType): void {
  const typeDir = path.join(MANIFESTS_DIR, typeName)
  const files = getJsonFiles(typeDir)

  if (files.length === 0) {
    console.log(`⚠ No JSON files found in ${typeName}/`)
    return
  }

  // Generate import statements - sort alphabetically by variable name
  const importData: ImportData[] = files.map(file => {
    const id = file.replace('.json', '')
    const varName = toPascalCase(id)
    const relativePath = `../../../manifests/${typeName}/${file}`
    return { varName, statement: `import ${varName} from '${relativePath}'`, sortKey: relativePath }
  })

  // Sort imports alphabetically by variable name
  importData.sort((a, b) => a.sortKey.localeCompare(b.sortKey, 'en', { numeric: true }))
  const imports = importData.map(item => item.statement).join('\n')

  // Generate array export using sorted variable names
  const arrayItems = importData.map(item => item.varName).join(',\n  ')

  // Generate type name (singular)
  const typeSingular = typeName.replace(/s$/, '')
  const TypeName = toPascalCase(typeSingular)

  // Get the first file (alphabetically) to extract type
  const firstVarName = importData[0]?.varName
  if (!firstVarName) {
    console.log(`⚠ No files found in ${typeName}/`)
    return
  }

  // Add appropriate type import based on manifest type
  const typeImportMap: Record<ManifestType, string> = {
    ides: 'ManifestIDE',
    clis: 'ManifestCLI',
    desktops: 'ManifestDesktop',
    models: 'ManifestModel',
    providers: 'ManifestProvider',
    extensions: 'ManifestExtension',
    vendors: 'ManifestVendor',
  }

  const manifestType = typeImportMap[typeName]
  const typeImport = manifestType
    ? `import type { ${manifestType} } from '../../types/manifests'\n`
    : ''

  const content = `/**
 * Auto-generated manifest index for ${typeName}
 * Generated by scripts/generate-manifest-indexes.ts
 * Do not edit manually - run the script to regenerate
 */

${imports}
${typeImport}
export const ${typeName}Data = [
  ${arrayItems},
]${manifestType ? ` as unknown as ${manifestType}[]` : ''}

export type ${TypeName} = typeof ${firstVarName}

export default ${typeName}Data
`

  const outputPath = path.join(OUTPUT_DIR, `${typeName}.ts`)
  fs.writeFileSync(outputPath, content, 'utf8')
  console.log(`✓ Generated ${typeName}.ts (${files.length} entries)`)
}

/**
 * Generate main index.ts file that exports all manifests
 */
function generateMainIndex(): void {
  // Generate all export statements
  const exportStatements: { type: string; data: string }[] = []
  for (const typeName of MANIFEST_TYPES) {
    const typeSingular = toPascalCase(typeName.replace(/s$/, ''))
    exportStatements.push({
      type: `export type { ${typeSingular} } from './${typeName}'`,
      data: `export { ${typeName}Data } from './${typeName}'`,
    })
  }

  // Sort exports alphabetically by type name and maintain type-before-data order
  const sortedExports = exportStatements
    .sort((a, b) => {
      const typeA = a.type.match(/\{ (\w+) \}/)?.[1] || ''
      const typeB = b.type.match(/\{ (\w+) \}/)?.[1] || ''
      return typeA.localeCompare(typeB, 'en', { numeric: true })
    })
    .flatMap(item => [item.type, item.data])
    .join('\n')

  const content = `/**
 * Auto-generated main manifest index
 * Generated by scripts/generate-manifest-indexes.ts
 * Do not edit manually - run the script to regenerate
 */

${sortedExports}
`

  const outputPath = path.join(OUTPUT_DIR, 'index.ts')
  fs.writeFileSync(outputPath, content, 'utf8')
  console.log(`✓ Generated index.ts`)
}

/**
 * Generate GitHub stars TypeScript file from centralized JSON
 */
function generateGithubStarsFile(): void {
  const githubStarsPath = path.join(__dirname, '..', '..', 'data', 'github-stars.json')

  if (!fs.existsSync(githubStarsPath)) {
    console.log('⚠ github-stars.json not found, skipping stars generation')
    return
  }

  const starsData = JSON.parse(fs.readFileSync(githubStarsPath, 'utf8'))

  const content = `/**
 * Auto-generated GitHub stars data
 * Generated by scripts/generate-manifest-indexes.ts
 * Do not edit manually - run the script to regenerate
 */

import githubStarsJson from '../../../data/github-stars.json'

export type GithubStarsData = Record<string, Record<string, number | null>>

export const githubStarsData = githubStarsJson as GithubStarsData

/**
 * Get GitHub stars for a specific product
 * @param category - The product category (extensions, clis, desktops, ides)
 * @param id - The product ID
 * @returns The number of stars (in thousands) or null if not available
 */
export function getGithubStars(category: string, id: string): number | null {
  return githubStarsData[category]?.[id] ?? null
}

export default githubStarsData
`

  const outputPath = path.join(OUTPUT_DIR, 'github-stars.ts')
  fs.writeFileSync(outputPath, content, 'utf8')

  // Count total entries
  const totalEntries = Object.values(starsData).reduce((sum: number, category: unknown) => {
    return sum + Object.keys(category as Record<string, unknown>).length
  }, 0)

  console.log(`✓ Generated github-stars.ts (${totalEntries} entries)`)
}

/**
 * Main execution
 */
function main(): void {
  console.log('='.repeat(60))
  console.log('Generate Manifest Index Files')
  console.log('='.repeat(60))

  // Ensure output directory exists
  ensureDir(OUTPUT_DIR)

  console.log('\n📝 Generating index files...\n')

  // Generate index file for each type
  for (const typeName of MANIFEST_TYPES) {
    generateIndexFile(typeName)
  }

  // Generate main index
  console.log('')
  generateMainIndex()

  // Generate GitHub stars file
  console.log('')
  generateGithubStarsFile()

  console.log(`\n${'='.repeat(60)}`)
  console.log('✅ All index files generated successfully!')
  console.log('='.repeat(60))

  // Format generated files and organize imports with the repository's Biome rules.
  console.log(`\n🎨 Checking generated files with Biome...`)
  try {
    execSync(`pnpm exec biome check --write ${OUTPUT_DIR}`, {
      cwd: path.join(__dirname, '../..'),
      stdio: 'inherit',
    })
    console.log(`✅ Formatting and import organization complete`)
  } catch (error) {
    console.error(`⚠️  Biome formatting failed:`, (error as Error).message)
  }
}

// Run the script
try {
  main()
} catch (error) {
  console.error('\n❌ Error generating index files:', (error as Error).message)
  console.error((error as Error).stack)
  process.exit(1)
}
